python: can't open file 'prepare_data.py': [Errno 2] No such file or directory
